### ISSUE TITLE
How to analysis local dataset?

### ISSUE THREAD

**Issue by KrithikaSubramanian** [niab/hwe#2]
Hi Sir/Madam,

I am Krithika S. I am going to analysis hwe for my dataset. Could you please guide me how I can parse my input to this hwe analysis.?

Thanks in advance

**Comment by nabramovs** [comment]
Hi Krithika,

Unfortunately, that's probably not possible. Most of this code was written specifically to analyse data in gnomAD jsons and will require a lot of changes to work with something else. You probably can reuse function Hardy_Weinberg_Equilibrium_exact_test_user_Kantale from hardy_weinberg.py file to calculate Hardy-Weinberg statistics in you analysis (it will work without other code from this repository). Most of the code in this function was written by Jan Wigginton (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1199378/), I've added only a small modification to calculate mid p-values instead of normal p-values.

If your dataset is in VCF format it might be easier to use PLINK instead of writing custom code (I didn't use it myself, so I cannot provide you a detailed guide how to use it):
https://www.cog-genomics.org/plink/1.9/basic_stats

Hope this helps.

Nikita

**Comment by nabramovs** [comment]
Not relevant.
